
name: 'Site Notifications'
description: 'Browser Website Notification and Daily Weather Report. (浏览器推送网站通知/每日天气预报推送)'

inputs:
  SUBSINFO:
    description: 'Your Website Subscription Code 你的网站订阅码'
    required: true
  LOCATION:
    description: 'Weather Forecast Location (This input marks push Weather Forecast Notification) 天气预报地点(该输入标志工作流进行天气预报报道)'
    required: false
  TITLE:
    description: 'Notification Title (This input marks push Customized Notification) 通知标题(该输入标志工作流进行自定义通知推送)'
    required: false
  OPTIONS:
    description: 'Notification Options (This input only works for Customized Notification) 通知选项(该输入仅对自定义通知推送起效)'
    required: false

runs:
  using: 'node12'
  main: 'dist/main.js'

branding:
  color: red
  icon: message-circle