name: 'Push Browser Notification and Daily Weather Report'
    
on:
  workflow_dispatch:  # Allow manual triggers
  schedule:
    - cron: '0 4 * * *' # Schedule on CST 12 everyday

jobs:
  bot:
    runs-on: ubuntu-latest
    steps:
        - name: Checkout
          uses: actions/checkout@v2
        - name: Push Browser Notification and Daily Weather Report
          uses: ./ # HollowMan6/Site-Notifications@main
          with:
            SUBSINFO: ${{ secrets.SUBSINFO }}
            LOCATION: ${{ secrets.LOCATION }}
            TITLE: ${{ secrets.TITLE }}
            OPTIONS: ${{ secrets.OPTIONS }}
